swagger: "2.0"
info:
  title: "Access NYC API"
  version: "1.0.0"
host: "my-gateway-cvn7805z.uc.gateway.dev"
schemes:
  - "https"
paths:
  /save-route:
    post:
      operationId: saveRoute
      summary: Save a route
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        "200":
          description: Success
        "500":
          description: Internal Server Error
      x-google-backend:
        address: https://my-gateway-cvn7805z.uc.gateway.dev
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query