openapi: 3.0.0
info:
  title: My API Gateway
  version: 1.0.0
paths:
  /save-route:
    post:
      summary: Save a route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
      x-google-backend:
        address: 'https://access-nyc-437201-k9.ue.r.appspot.com'
